"""update_vector_dim_3072_and_add_page_number

Revision ID: 3efe0f463a52
Revises: 47e12336604f
Create Date: 2026-08-13 21:10:12.448148

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3efe0f463a52'
down_revision: Union[str, Sequence[str], None] = '47e12336604f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
