"""add_quiz_options_and_flashcard_source_page

Revision ID: 409bfba3c6b3
Revises: 3efe0f463a52
Create Date: 2026-08-13 21:49:10.743813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409bfba3c6b3'
down_revision: Union[str, Sequence[str], None] = '3efe0f463a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('source_page', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('source_page', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('questions', 'source_page')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'options')
    op.drop_column('flashcards', 'source_page')
    # ### end Alembic commands ###
