"""add_document_metadata_fields

Revision ID: 47e12336604f
Revises: df8b1983072f
Create Date: 2026-08-13 16:40:39.097042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e12336604f'
down_revision: Union[str, Sequence[str], None] = 'df8b1983072f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
